# A few notes!
# The hub -> authentic class defaults to "dummy"
# We shouldn't need any image pull secrets assuming public
# There is a note about the database being a sqlite pvc
# (and a TODO for better solution for Kubernetes)

# This is the concurrent spawn limit, likely should be increased (deafults to 64)
hub:
  concurrentSpawnLimit: 10
  config:
    DummyAuthenticator:
      password: butter
    JupyterHub:
      admin_access: true
      authenticator_class: dummy

  # This is the image I built based off of jupyterhub/k8s-hub, 3.0.2 at time of writing this
  image: 
    name: ghcr.io/flux-framework/flux-jupyter-hub
    tag: "hpcic-2024"
    pullPolicy: Always

# https://z2jh.jupyter.org/en/latest/administrator/optimization.html#scaling-up-in-time-user-placeholders
scheduling:
  podPriority:
    enabled: true
  userPlaceholder:
    # Specify 3 dummy user pods will be used as placeholders
    replicas: 3

# This is the "spawn" image
singleuser:
  image:
    name: ghcr.io/flux-framework/flux-jupyter-spawn
    tag: "hpcic-2024"
    pullPolicy: Always
  cpu:
    limit: 1
  memory:
    limit: '4G'
  cmd: /entrypoint.sh

  # This is how we get the tutorial files added
  storage:
    type: none

    # gitRepo volume is deprecated so we need another way
    # https://kubernetes.io/docs/concepts/storage/volumes/#gitrepo
    extraVolumes:
      - name: flux-tutorial
        emptyDir: {}
    extraVolumeMounts:
      - name: flux-tutorial
        mountPath: /home/jovyan/
